/**
 * Simple template engine for dynamic content injection
 */

import { escapeHtml, replaceMetaTag, replaceTitle } from './html-utils.js';

/**
 * Inject guide data into HTML template
 * @param {string} templateHTML - Base HTML template
 * @param {Object} guide - Guide data from database
 * @returns {string} - Modified HTML with guide data
 */
export function injectGuideData(templateHTML, guide) {
  let html = templateHTML;
  
  // Update document metadata
  html = replaceTitle(html, `${guide.title} - ZGRAD Help Guide`);
  html = replaceMetaTag(html, 'description', guide.description);
  html = replaceMetaTag(html, 'author', guide.author_name);
  
  // Update canonical and URLs
  html = html.replace(
    /<link rel="canonical" href=".*?">/,
    `<link rel="canonical" href="https://zgrad.gg/guides/${escapeHtml(guide.slug)}">`
  );
  
  // Update Open Graph meta tags
  html = replaceMetaTag(html, 'og:title', `${guide.title} - ZGRAD`, true);
  html = replaceMetaTag(html, 'og:description', guide.description, true);
  html = replaceMetaTag(html, 'og:url', `https://zgrad.gg/guides/${guide.slug}`, true);
  
  // Update Twitter Card meta tags
  html = replaceMetaTag(html, 'twitter:title', `${guide.title} - ZGRAD`);
  html = replaceMetaTag(html, 'twitter:description', guide.description);
  
  // Update thumbnail/images if provided
  if (guide.thumbnail) {
    html = replaceMetaTag(html, 'thumbnail', guide.thumbnail);
    html = replaceMetaTag(html, 'og:image', guide.thumbnail, true);
    html = replaceMetaTag(html, 'twitter:image', guide.thumbnail);
  }
  
  // Update page title and subtitle
  const titleUpper = guide.title.toUpperCase();
  html = html.replace(
    /<h1 class="guide-title" data-text=".*?">.*?<\/h1>/,
    `<h1 class="guide-title" data-text="${escapeHtml(titleUpper)}">${escapeHtml(titleUpper)}</h1>`
  );
  
  html = html.replace(
    /<p class="guide-subtitle">.*?<\/p>/,
    `<p class="guide-subtitle">${escapeHtml(guide.description || '')}</p>`
  );
  
  // Inject the actual guide content
  html = html.replace(
    /<div class="guide-content">.*?<\/div>\s*<\/div>\s*<script/s,
    `<div class="guide-content">${guide.content}</div></div>
    
    <!-- Footer -->
    <footer class="footer">
        <!-- Footer content will be generated by JavaScript -->
    </footer>
    
    <script`
  );
  
  return html;
}

